### ISSUE TITLE
Can't install add-On in Blender 2.83

### ISSUE THREAD

**Issue by klamauk** [agapas/separate-curves#2]
I just wanted to thank you for this great script.  It seems i can't install it in the blender 2.83 alpha. Maybe something is broken.

**Comment by agapas** [comment]
Hi, I just tried to install it on my machine (on the Blender version from today, February 28) and everything works fine for me. I'm not sure what can be the reason in your case. Generally I support only official versions of Blender and the 2.83 alpha is experimental one. It means that it's still under development and it can contain plenty of bugs... My advice (in the case if you still need this version): you could check errors in Blender's console (Window/Toggle System Console). It could give you an idea what is wrong.

**Comment by klamauk** [comment]
Thanks for your reply. It seemed something was wrong with the zip from GitHub. After unpacking and zipping again I could install the add-on with no problems. Maybe something went wrong with my download. Nevermind. It would be great if your add-on was contributed to the main branch of Blender. Its so useful when working with curves/dxf data.
